name: Create a comment on new issue

on:
  issues:
    types: [opend]
jobs:
  comments-with-action:
    runs-on: ubuntu-lates
    steps:
      - name: "dump github contest"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
  
