name: Workflow exmpale 1

on:
  push:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World"
        shell: bash
        
  goodby:
    runs-on: ubuntu-latest
    steps:
      - name: GoodBy
        run: echo "Good By"
        shell: bash
  
